pde:
  nu: 0.1

dataset:
  data_path: 'home/Data/FNO/1D_Burgers_256_{}.npy'
  n_train: 1000
  n_test: 20000
  batch_size: 64
  test_batch_sizes: 64
  positional_encoding: true
  data_augmentation: true

model:
  n_modes_height: 2
  n_modes_width: 32
  hidden_channels: 24
  out_channels: 1
  projection_channels: 24
  n_layers: 5
  norm: 'group_norm'
  skip: 'linear'
  use_mlp: true
  factorization: 'Tucker'
  rank: 0.05
  save_path: 'FNO/model_saved/model_burgers1d_256_0.05_{}.pth'

