pde:
  nu: 0.0001

dataset:
  data_path: 'home/Data/FNO/ns_128_T50_{}.pt'
  n_train: 1000
  n_test: 10000
  batch_size: 64
  test_batch_sizes: 64
  positional_encoding: true
  data_augmentation: false

model:
  n_modes_height: 48
  n_modes_width: 48
  hidden_channels: 64
  out_channels: 1
  projection_channels: 256
  norm: 'group_norm'
  skip: 'linear'
  use_mlp: true
  factorization: 'Tucker'
  rank: 1
  save_path: 'FNO/model_saved/model_navier_stokes_128_T50_{}.pth'
